name: Python
on:
  push:
    branches:
      - main
jobs:
  sonarcloud:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pytest-cov python-utils
      - name: Running pytest
        run: pytest -v --cov --cov-report=xml --cov-report=html
      - uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: htmlcov
      - name: SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.core.codeCoveragePlugin=cobertura
            -Dsonar.organization=olbiwan
            -Dsonar.projectKey=tictactoe-python
            -Dsonar.projectVersion=1.0.0
            -Dsonar.python.coverage.reportPaths=*coverage*.xml
            -Dsonar.sources=./python/